# Workflow Name
name: Deploy with Lighthouse Badges and Reports

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Generate Lighthouse Badges
      - name: Generate Lighthouse Badges
        run: |
          npx lighthouse-badges --url=https://steven2k2.github.io --output-path=badges
        env:
          NODE_ENV: production

      # Step 5: Generate Lighthouse Report
      - name: Generate Lighthouse Report
        run: |
          lhci autorun --collect.url=https://steven2k2.github.io --output-path ./public/reports

      # Step 6: Get Last Commit Date
      - name: Get Last Commit Date
        run: |
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=iso)
          echo "{\"lastUpdated\": \"$LAST_COMMIT_DATE\"}" > last-updated.json

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public