# Workflow Name
name: Deploy with Lighthouse Badges

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Lighthouse and generate badges
      - name: Generate Lighthouse Badges
        run: |
          npx lighthouse-badges --url=https://steven2k2.github.io --output-path=badges
        env:
          NODE_ENV: production

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .