name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse
        run: |
          lhci autorun --collect.url=https://steven2k2.github.io

      - name: Generate Lighthouse Badges
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"url":"https://steven2k2.github.io"}' \
          https://lighthouse-badges.netlify.app/api/generate > badges.json

      - name: Extract Badges
        run: |
          mkdir -p public/badges
          jq -r '.[] | .svg' badges.json | while read -r badge; do
            name=$(echo "$badge" | jq -r '.label' | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
            content=$(echo "$badge" | jq -r '.svg')
            echo "$content" > "public/badges/$name.svg"
          done

      - name: Deploy Badges
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public