name: Lighthouse CI with Badges and Bootstrap Deployment

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli lighthouse-badges

      - name: Run Lighthouse
        run: |
          lhci autorun --collect.url=https://steven2k2.github.io

      - name: Generate Lighthouse Badges
        run: |
          lighthouse-badges --url https://steven2k2.github.io --output-path ./public/badges

      - name: Prepare Deployment Files
        run: |
          mkdir -p ./public
          cp -R ./badges ./public/badges
          cp -R ./* ./public/ # Copies all Bootstrap files into the public folder, excluding `.github` and other ignored files

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public